export const GET_BLOGS_REQUEST = "GET_BLOGS_REQUEST";
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_BLOGS_FAILURE = "GET_BLOGS_FAILURE";
export const GET_OWN_BLOGS = "GET_OWN_BLOGS"; // not yet needed
export const GET_BLOGS_BY_USER_ID = "GET_BLOGS_BY_USER_ID";
export const ADD_BLOG = "ADD_BLOG";

export const CHANGE_USERID = "CHANGE_USERID";

export const GET_USER_INFO_REQUEST = "GET_USER_INFO_REQUEST";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILURE = "GET_USER_INFO_FAILURE";

export const GET_FRIEND_INFO_REQUEST = "GET_FRIEND_INFO_REQUEST";
export const GET_FRIEND_INFO_SUCCESS = "GET_FRIEND_INFO_SUCCESS";
export const GET_FRIEND_INFO_FAILURE = "GET_FRIEND_INFO_FAILURE";

export const CHANGE_SELECTED_LOCATION = "CHANGE_SELECTED_LOCATION";

export const GET_POINTS_OF_INTEREST_SUCCESS = "GET_POINTS_OF_INTEREST_SUCCESS";
export const GET_ATTRACTIONS_SUCCESS = "GET_ATTRACTIONS_SUCCESS";
export const GET_BASIC_LOCATION_INFO_SUCCESS = "GET_BASIC_LOCATION_INFO_SUCCESS";

export const ADD_FAV_DESTINATION_SUCCESS = "ADD_FAV_DESTINATION_SUCCESS";
export const GET_FAV_DESTINATIONS_SUCCESS = "GET_FAV_DESTINATIONS_SUCCESS";
// export const DELETE_FAV_DESTINATION_SUCCESS = "DELETE_FAV_DESTINATION_SUCCESS";

export const ADD_VISITED_DESTINATION_SUCCESS = "ADD_VISITED_DESTINATION_SUCCESS";
export const GET_VISITED_DESTINATIONS_SUCCESS = "GET_VISITED_DESTINATIONS_SUCCESS";
// export const DELETE_VISITED_DESTINATION_SUCCESS = "DELETE_VISITED_DESTINATION_SUCCESS";

export const SET_HEADER = "SET_HEADER";
export const RCV_ERROR = "RCV_ERROR";
export const ADD_ERROR = "ADD_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
