const types = {
  ADD_BLOG: "ADD_BLOG",
  GET_BLOGS_REQUEST: "GET_BLOGS_REQUEST",
  GET_BLOGS_SUCCESS: "GET_BLOGS_SUCCESS",
  GET_BLOGS_FAILURE: "GET_BLOGS_FAILURE",
  GET_BLOGS: "GET_BLOGS",
  GET_OWN_BLOGS: "GET_OWN_BLOGS", // not yet needed
  GET_POINTS_OF_INTEREST_SUCCESS: "GET_POINTS_OF_INTEREST_SUCCESS",
  GET_ATTRACTIONS_SUCCESS: "GET_ATTRACTIONS_SUCCESS",
  ADD_FAV_DESTINATION: "ADD_FAV_DESTINATION",
  GET_FAV_DESTINATIONS: "GET_FAV_DESTINATIONS",
  ADD_DESTINATIONS_PAST: "ADD_DESTINATIONS_PAST",
  ADD_DESTINATIONS_FUTURE: "ADD_DESTINATIONS_FUTURE",
  GET_VISITED_DESTINATIONS: "GET_VISITED_DESTINATIONS",
  SET_HEADER: "SET_HEADER",
  RCV_ERROR: "RCV_ERROR",
  ADD_ERROR: "ADD_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR"
};

export default types;
