export const GET_BLOGS_REQUEST = "GET_BLOGS_REQUEST";
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_BLOGS_FAILURE = "GET_BLOGS_FAILURE";
export const GET_OWN_BLOGS = "GET_OWN_BLOGS"; // not yet needed
export const GET_BLOGS_BY_USER_ID = "GET_BLOGS_BY_USER_ID";

export const BLOG_CREATING = "BLOG_CREATING";
export const BLOG_CREATE_SUCCESS = "BLOG_CREATE_SUCCESS";
export const BLOG_CREATE_ERROR = "BLOG_CREATE_ERROR";

export const CHANGE_USERID = "CHANGE_USERID";
export const CHANGE_FRIENDSID = "CHANGE_FRIENDSID";

export const GET_USER_INFO_REQUEST = "GET_USER_INFO_REQUEST";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILURE = "GET_USER_INFO_FAILURE";

export const GET_FRIENDS_LIST_REQUEST = "GET_FRIENDS_LIST_REQUEST";
export const GET_FRIENDS_LIST_SUCCESS = "GET_FRIENDS_LIST_SUCCESS";
export const GET_FRIENDS_LIST_FAILURE = "GET_FRIENDS_LIST_FAILURE";

export const GET_FRIEND_INFO_REQUEST = "GET_FRIEND_INFO_REQUEST";
export const GET_FRIEND_INFO_SUCCESS = "GET_FRIEND_INFO_SUCCESS";
export const GET_FRIEND_INFO_FAILURE = "GET_FRIEND_INFO_FAILURE";

export const CHANGE_SELECTED_LOCATION = "CHANGE_SELECTED_LOCATION";

export const GET_POINTS_OF_INTEREST_SUCCESS = "GET_POINTS_OF_INTEREST_SUCCESS";
export const GET_ATTRACTIONS_SUCCESS = "GET_ATTRACTIONS_SUCCESS";
export const GET_BASIC_LOCATION_INFO_SUCCESS = "GET_BASIC_LOCATION_INFO_SUCCESS";
export const GET_VISITED_COUNT = "GET_VISITED_COUNT";
export const GET_FAVE_COUNT = "GET_FAVE_COUNT";

export const ADD_FAV_DESTINATION_SUCCESS = "ADD_FAV_DESTINATION_SUCCESS";
export const GET_FAV_DESTINATIONS_SUCCESS = "GET_FAV_DESTINATIONS_SUCCESS";
// export const DELETE_FAV_DESTINATION_SUCCESS = "DELETE_FAV_DESTINATION_SUCCESS";

export const ADD_VISITED_DESTINATION_SUCCESS = "ADD_VISITED_DESTINATION_SUCCESS";
export const GET_VISITED_DESTINATIONS_SUCCESS = "GET_VISITED_DESTINATIONS_SUCCESS";
// export const DELETE_VISITED_DESTINATION_SUCCESS = "DELETE_VISITED_DESTINATION_SUCCESS";

export const SET_HEADER = "SET_HEADER";
export const RCV_ERROR = "RCV_ERROR";
export const ADD_ERROR = "ADD_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_USER = "AUTH_USER";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
